return function()
    -- ============================================================
    -- Tex
    -- ============================================================
    vim.api.nvim_create_autocmd("FileType", {
        pattern = {
            "tex",
        },
        callback = function()
            vim.keymap.set("n", "<C-c><C-c>c", function()
                vim.cmd("VimtexCompile")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCompile" })
            vim.keymap.set("n", "<C-c><C-c>g", function()
                vim.cmd("VimtexCompileSS")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCompileSS" })
            vim.keymap.set("n", "<C-c><C-c>C", function()
                vim.cmd("VimtexCompileSelected")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCompileSelected" })
            vim.keymap.set("n", "<C-c><C-c>o", function()
                vim.cmd("VimtexCompileOutput")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCompileOutput" })
            vim.keymap.set("n", "<C-c><C-c>s", function()
                vim.cmd("VimtexStop")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexStop" })
            vim.keymap.set("n", "<C-c><C-c>S", function()
                vim.cmd("VimtexStopAll")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexStopAll" })
            vim.keymap.set("n", "<C-c><C-c>r", function()
                vim.cmd("VimtexReload")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexReload" })
            vim.keymap.set("n", "<C-c><C-c>R", function()
                vim.cmd("VimtexReloadState")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexReloadState" })
            vim.keymap.set("n", "<C-c><C-c>w", function()
                vim.cmd("VimtexCountWords")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCountWords" })
            vim.keymap.set("n", "<C-c><C-c>W", function()
                vim.cmd("VimtexCountWords!")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCountWords!" })
            vim.keymap.set("n", "<C-c><C-c>t", function()
                vim.cmd("VimtexCountLetters")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCountLetters" })
            vim.keymap.set("n", "<C-c><C-c>T", function()
                vim.cmd("VimtexCountLetters!")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexCountLetters!" })
            vim.keymap.set("n", "<C-c><C-c>f", function()
                vim.cmd("VimtexInfo")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexInfo" })
            vim.keymap.set("n", "<C-c><C-c>F", function()
                vim.cmd("VimtexInfo!")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexInfo!" })
            vim.keymap.set("n", "<C-c><C-c>u", function()
                vim.cmd("VimtexStatus")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexStatus" })
            vim.keymap.set("n", "<C-c><C-c>U", function()
                vim.cmd("VimtexStatus!")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexStatus!" })
            vim.keymap.set("n", "<C-c><C-c>x", function()
                vim.cmd("VimtexClean")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexClean" })
            vim.keymap.set("n", "<C-c><C-c>X", function()
                vim.cmd("VimtexClean!")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexClean!" })
            vim.keymap.set("n", "<C-c><C-c>m", function()
                vim.cmd("VimtexLog")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexLog" })
            vim.keymap.set("n", "<C-c><C-c>e", function()
                vim.cmd("VimtexErrors")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexErrors" })
            vim.keymap.set("n", "<C-c><C-c>K", function()
                vim.cmd("VimtexTocToggle")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexTocToggle" })
            vim.keymap.set("n", "<C-c><C-c>d", function()
                vim.cmd("VimtexDocPackage")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexDocPackage" })
            vim.keymap.set("n", "<C-c><C-c>n", function()
                vim.cmd("VimtexToggleMain")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexToggleMain" })
            vim.keymap.set("n", "<C-c><C-c>p", function()
                vim.cmd("VimtexImapsList")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexImapsList" })
            vim.keymap.set("n", "<C-c><C-c>v", function()
                vim.cmd("VimtexView")
            end, { buffer = true, noremap = true, silent = true, desc = "VimtexView" })
        end,
        group = "MyIDE",
    })
end
